### ISSUE TITLE
this person

### ISSUE THREAD

**Issue by Freddyhun** [sketchycrypt/sftwaremain#2]
this fuckin guy closed my issue

**Comment by sketchycrypt** [comment]
your issue was not helpful cause you can't even type yet OMEAGLUL

**Comment by Freddyhun** [comment]
nigga go suck my nuts you inane, autistic ass mf bitchass cant even fucking open a door with his own hands nigga gotta call up my nigga jerome then suck him off for jerome to open the fuckin door then have jerome push his fuckin disabled ass through that door

**Comment by Freddyhun** [comment]
fuckin beep beep wheelchair lookin ass nigga
