### ISSUE TITLE
mobile version sucks :/

### ISSUE THREAD

**Issue by Freddyhun** [sketchycrypt/sftwaremain#3]
the mobile version sucks dick,  update it

**Comment by sketchycrypt** [comment]
fuck you but sure

**Comment by Freddyhun** [comment]
booba

**Comment by Freddyhun** [comment]
awooga

**Comment by Freddyhun** [comment]
![image](https://user-images.githubusercontent.com/80177953/110224721-68249700-7ede-11eb-9308-4d29e6d89eb3.png)

**Comment by sketchycrypt** [comment]
fixed
